<a href="https://colab.research.google.com/github/TJSidhu1/Python-Libraries/blob/main/numpyRevision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [30]:
a = np.array([[1,2,"Sam",3], [4,5,6,7]])
a

array([['1', '2', 'Sam', '3'],
       ['4', '5', '6', '7']], dtype='<U21')

In [31]:
a.size

8

In [32]:
a.ndim

2

In [33]:
a.shape

(2, 4)

In [34]:
a.dtype

dtype('<U21')

In [12]:
b = {1,2,3,4}

In [18]:
b

{1, 2, 3, 4}

In [41]:
np.zeros(3, dtype= float)

array([0., 0., 0.])

In [45]:
np.ones(4, dtype= float)

array([1., 1., 1., 1.])

In [46]:
np.arange(2,6)

array([2, 3, 4, 5])

In [48]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [49]:
np.arange(0,5,2)

array([0, 2, 4])

In [51]:
np.linspace(0,10,2)

array([ 0., 10.])

In [60]:
c = np.sort(np.array([2,1,5,3,7,4,6,8]))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
d = np.array([1,2,3])
d

array([1, 2, 3])

In [69]:
e = np.concatenate((c,d))
e

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3])

In [70]:
np.sort(e)

array([1, 1, 2, 2, 3, 3, 4, 5, 6, 7, 8])

In [71]:
a = np.array([1, 2, 3])
print(a.shape)           # (3,)

# Add new axis (make it a column vector)
a_col = a[:, np.newaxis]
print(a_col.shape)       # (3, 1)

# Add new axis (make it a row vector)
a_row = a[np.newaxis, :]
print(a_row.shape)       # (1, 3)


(3,)
(3, 1)
(1, 3)


In [72]:
a = np.array([1, 2, 3])
print(a.shape)             # (3,)

# Add a new axis at position 0
a_exp_0 = np.expand_dims(a, axis=0)
print(a_exp_0.shape)       # (1, 3)

# Add a new axis at position 1
a_exp_1 = np.expand_dims(a, axis=1)
print(a_exp_1.shape)       # (3, 1)


(3,)
(1, 3)
(3, 1)


In [73]:
a.transpose()

array([1, 2, 3])

In [75]:
np.flip(a)

array([3, 2, 1])

In [21]:
x = np.array([[1,2,3],[4,5,5]])
x

array([[1, 2, 3],
       [4, 5, 5]])

In [22]:
a = x.flatten()
a

array([1, 2, 3, 4, 5, 5])

In [23]:
a[0] = 100
a

array([100,   2,   3,   4,   5,   5])

In [24]:
x

array([[1, 2, 3],
       [4, 5, 5]])

In [13]:
a

array([1, 2, 3, 4, 5, 5])

In [26]:
b = x.ravel()         #doesn't make a copy so any changes in the ravel will show in the original unlike flatten
b

array([1, 2, 3, 4, 5, 5])

In [27]:
b[0] = 200

In [28]:
b

array([200,   2,   3,   4,   5,   5])

In [29]:
x

array([[200,   2,   3],
       [  4,   5,   5]])